name: Nightly Build

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build pdf
        shell: bash
        run: |
          cd latex/src
          sed '/includeonly/d' main.tex > Cpp17.tex
          tectonic Cpp17.tex

      - name: upload pdf file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latex/src/Cpp17.pdf
          asset_name: Cpp17.pdf
          tag: refs/tags/v1.0
          overwrite: true
